# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adc_port.xdc

# Block Designs: bd/EEG_Signal_Processing/EEG_Signal_Processing.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EEG_Signal_Processing || ORIG_REF_NAME==EEG_Signal_Processing} -quiet] -quiet

# IP: bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EEG_Signal_Processing_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==EEG_Signal_Processing_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_proc_sys_reset_0_0/EEG_Signal_Processing_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EEG_Signal_Processing_proc_sys_reset_0_0 || ORIG_REF_NAME==EEG_Signal_Processing_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_smartconnect_0_0/EEG_Signal_Processing_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EEG_Signal_Processing_smartconnect_0_0 || ORIG_REF_NAME==EEG_Signal_Processing_smartconnect_0_0} -quiet] -quiet

# IP: bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_axi_iic_0_0/EEG_Signal_Processing_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==EEG_Signal_Processing_axi_iic_0_0 || ORIG_REF_NAME==EEG_Signal_Processing_axi_iic_0_0} -quiet] -quiet

# XDC: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.gen/sources_1/bd/EEG_Signal_Processing/EEG_Signal_Processing_ooc.xdc
