# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.srcs/sources_1/bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'EEG_Signal_Processing_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.gen/sources_1/bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EEG_Signal_Processing_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.gen/sources_1/bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EEG_Signal_Processing_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.srcs/sources_1/bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'EEG_Signal_Processing_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.gen/sources_1/bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EEG_Signal_Processing_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dragonlord/Desktop/EEG_Signal_Processing/EEG_Signal_Processing.gen/sources_1/bd/EEG_Signal_Processing/ip/EEG_Signal_Processing_zynq_ultra_ps_e_0_0/EEG_Signal_Processing_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EEG_Signal_Processing_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
